// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.AvroSchema
{
    using EventBus;
    using global::Avro;
    using global::Avro.Specific;
    using System.Collections.Generic;

    public partial class OrderCreatedIntegrationEvent : IntegrationEvent, ISpecificRecord
    {
        public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""OrderCreatedIntegrationEvent"",""namespace"":""Ordering.AvroSchema"",""fields"":[{""name"":""OrderId"",""type"":""int""},{""name"":""Products"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Product"",""namespace"":""Ordering.AvroSchema"",""fields"":[{""name"":""ProductName"",""type"":""string""},{""name"":""Quantity"",""type"":""int""},{""name"":""UnitPrice"",""type"":""double""}]}}}]}");
        private int _OrderId;
        private IList<Ordering.AvroSchema.Product> _Products;
        public virtual Schema Schema
        {
            get
            {
                return OrderCreatedIntegrationEvent._SCHEMA;
            }
        }
        public int OrderId
        {
            get
            {
                return this._OrderId;
            }
            set
            {
                this._OrderId = value;
            }
        }
        public IList<Ordering.AvroSchema.Product> Products
        {
            get
            {
                return this._Products;
            }
            set
            {
                this._Products = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.OrderId;
                case 1: return this.Products;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.OrderId = (System.Int32)fieldValue; break;
                case 1: this.Products = (IList<Ordering.AvroSchema.Product>)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
