// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Dispatch.AvroSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
    using EventBus;
    using global::Avro;
	using global::Avro.Specific;
	
	public partial class OrderDispatchedIntegrationEvent : IntegrationEvent, ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"OrderDispatchedIntegrationEvent\",\"namespace\":\"Dispatch.A" +
				"vroSchema\",\"fields\":[{\"name\":\"DispatchOrderId\",\"type\":\"int\"},{\"name\":\"OrderId\",\"" +
				"type\":\"int\"},{\"name\":\"IsDispatched\",\"type\":\"boolean\"}]}");
		private int _DispatchOrderId;
		private int _OrderId;
		private bool _IsDispatched;
		public virtual Schema Schema
		{
			get
			{
				return OrderDispatchedIntegrationEvent._SCHEMA;
			}
		}
		public int DispatchOrderId
		{
			get
			{
				return this._DispatchOrderId;
			}
			set
			{
				this._DispatchOrderId = value;
			}
		}
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public bool IsDispatched
		{
			get
			{
				return this._IsDispatched;
			}
			set
			{
				this._IsDispatched = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DispatchOrderId;
			case 1: return this.OrderId;
			case 2: return this.IsDispatched;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DispatchOrderId = (System.Int32)fieldValue; break;
			case 1: this.OrderId = (System.Int32)fieldValue; break;
			case 2: this.IsDispatched = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
