// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ordering.AvroSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Product : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"Ordering.AvroSchema\",\"fields\":[{\"n" +
				"ame\":\"ProductName\",\"type\":\"string\"},{\"name\":\"Quantity\",\"type\":\"int\"},{\"name\":\"Un" +
				"itPrice\",\"type\":\"double\"}]}");
		private string _ProductName;
		private int _Quantity;
		private double _UnitPrice;
		public virtual Schema Schema
		{
			get
			{
				return Product._SCHEMA;
			}
		}
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				this._ProductName = value;
			}
		}
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				this._Quantity = value;
			}
		}
		public double UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				this._UnitPrice = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ProductName;
			case 1: return this.Quantity;
			case 2: return this.UnitPrice;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ProductName = (System.String)fieldValue; break;
			case 1: this.Quantity = (System.Int32)fieldValue; break;
			case 2: this.UnitPrice = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
