// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Producer.AvroSchema
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class UserCreatedIntegrationEvent : EventBus.IntegrationEvent, ISpecificRecord
    {
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""UserCreatedIntegrationEvent"",""namespace"":""Producer.AvroSchema"",""fields"":[{""name"":""UserId"",""type"":""int""},{""name"":""FirstName"",""type"":""string""},{""name"":""LastName"",""type"":""string""},{""name"":""FullName"",""type"":""string""},{""name"":""Age"",""type"":""int""}]}");
		private int _UserId;
		private string _FirstName;
		private string _LastName;
		private string _FullName;
		private int _Age;
		public virtual Schema Schema
		{
			get
			{
				return UserCreatedIntegrationEvent._SCHEMA;
			}
		}
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				this._UserId = value;
			}
		}
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				this._FirstName = value;
			}
		}
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				this._LastName = value;
			}
		}
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				this._FullName = value;
			}
		}
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				this._Age = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UserId;
			case 1: return this.FirstName;
			case 2: return this.LastName;
			case 3: return this.FullName;
			case 4: return this.Age;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UserId = (System.Int32)fieldValue; break;
			case 1: this.FirstName = (System.String)fieldValue; break;
			case 2: this.LastName = (System.String)fieldValue; break;
			case 3: this.FullName = (System.String)fieldValue; break;
			case 4: this.Age = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
